version: "3"

services:
  postgres:
    image: postgres
    ports:
      - "6543:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: Firdaus
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: HashTagDB

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: salpiedah@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Kill8057
    depends_on:
      - postgres

  django:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
